name: Grid and Mesh Solver
on: [push]

env:
  PETSC_VERSION: '3.24.2'
  PETSC_CACHE_VERSION: '1'
  HOMEBREW_NO_ANALYTICS: 'ON'     # Make Homebrew installation a little quicker
  HOMEBREW_NO_AUTO_UPDATE: 'ON'
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: 'ON'
  HOMEBREW_NO_GITHUB_API: 'ON'
  HOMEBREW_NO_INSTALL_CLEANUP: 'ON'

jobs:

  macos_arm_gcc:

    runs-on: macos-14

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          brew install make gcc
          echo "MAKE=$(brew --prefix)/bin/gmake" >> $GITHUB_ENV

      - name: PETSc - Cache download
        id: petsc-download
        uses: actions/cache@v4
        with:
          path: download
          key: petsc-${{ env.PETSC_VERSION }}.tar.gz

      - name: PETSc - Cache Installation
        id: petsc-install
        uses: actions/cache@v4
        with:
          path: petsc-${{ env.PETSC_VERSION }}
          key: petsc-${{ env.PETSC_VERSION }}-macos-arm-${{ env.PETSC_CACHE_VERSION }}
          restore-keys: |
            petsc-${{ env.PETSC_VERSION }}-macos-arm-

      - name: PETSc - Download
        if: steps.petsc-download.outputs.cache-hit != 'true'
        run: |
          mkdir -p download
          curl -sSL https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-${PETSC_VERSION}.tar.gz -o download/petsc-${PETSC_VERSION}.tar.gz

      - name: PETSc - Env
        run: |
          echo "PETSC_DIR=${PWD}/petsc-${PETSC_VERSION}" >> $GITHUB_ENV
          echo "PETSC_ARCH=macos-arm" >> $GITHUB_ENV

      - name: PETSc - Prepare
        if: steps.petsc-install.outputs.cache-hit != 'true'
        run: |
          tar -xf download/petsc-${PETSC_VERSION}.tar.gz -C .
          printenv >> $GITHUB_ENV

      - name: PETSc - Installation
        if: steps.petsc-install.outputs.cache-hit != 'true'
        run: |
          FC=$(ls /opt/homebrew/bin/gfortran-* | sort -V | tail -1)
          cd petsc-${PETSC_VERSION}
          ./configure \
          --with-cc=clang --with-cxx=clang++ --with-fc=$FC \
          --download-openmpi --download-openmpi-configure-arguments="CC=clang CXX=clang++ FC=$FC" \
          --download-hdf5 --with-hdf5-fortran-bindings=1 --with-hdf5-cxx-bindings=1 \
          --download-fftw --download-boost \
          --download-zlib \
          --with-mpi-f90module-visibility=1 || (cat configure.log && exit 1)
          ${MAKE} all || (cat configure.log && exit 1)

      - name: DAMASK - Compile
        run: |
          cmake -B build -DGRID=ON -DMESH=ON -DCMAKE_INSTALL_PREFIX=${PWD}
          cmake --build build --parallel
          cmake --install build

      - name: DAMASK - Run
        run: |
          ./build/src/DAMASK_grid -l tensionX.yaml -g 20grains16x16x16.vti -m material.yaml -w examples/grid
          ./build/src/DAMASK_mesh -l tensionZ_3g.yaml -g cube_3grains.msh -m material.yaml -w examples/mesh
