name: Grid and Mesh Solver
on: [push]

env:
  PETSC_VERSION: '3.23.3'
  HOMEBREW_NO_ANALYTICS: 'ON'     # Make Homebrew installation a little quicker
  HOMEBREW_NO_AUTO_UPDATE: 'ON'
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: 'ON'
  HOMEBREW_NO_GITHUB_API: 'ON'
  HOMEBREW_NO_INSTALL_CLEANUP: 'ON'

jobs:
  macos_build:
    runs-on: macos-latest

    strategy:
      matrix:
        gcc_v: [15]
      fail-fast: false

    env:
      GCC_V: ${{ matrix.gcc_v }}

    steps:

      - uses: actions/checkout@v4

      - name: GCC - Install
        run: |
          brew install gcc@${GCC_V}
          echo "FC=$(brew --prefix gcc@${GCC_V})/bin/gfortran-${GCC_V}" >> $GITHUB_ENV
          echo "CC=$(brew --prefix gcc@${GCC_V})/bin/gcc-${GCC_V}" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix gcc@${GCC_V})/bin/g++-${GCC_V}" >> $GITHUB_ENV

      - name: Boost - Install with GCC
        run: |
          brew install boost --build-from-source --cc=gcc-${GCC_V} --cxx=g++-${GCC_V}
          echo "BOOST_ROOT=$(brew --prefix boost)" >> $GITHUB_ENV

      - name: PETSc - Cache download
        id: petsc-download
        uses: actions/cache@v4
        with:
          path: download
          key: petsc-${{ env.PETSC_VERSION }}.tar.gz

      - name: PETSc - Download
        if: steps.petsc-download.outputs.cache-hit != 'true'
        run: |
          wget -q https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-${PETSC_VERSION}.tar.gz -P download

      - name: PETSc - Prepare
        run: |
          tar -xf download/petsc-${PETSC_VERSION}.tar.gz -C .
          export PETSC_DIR=${PWD}/petsc-${PETSC_VERSION}
          export PETSC_ARCH=gcc${GCC_V}
          printenv >> $GITHUB_ENV

      - name: PETSc - Cache Installation
        id: petsc-install
        uses: actions/cache@v4
        with:
          path: petsc-${{ env.PETSC_VERSION }}
          key: petsc-${{ env.PETSC_VERSION }}-macos-${{ hashFiles('**/petscversion.h') }}

      - name: PETSc - Installation
        run: |
          cd petsc-${PETSC_VERSION}
          ./configure --with-fc=$FC --with-cc=$CC --with-cxx=$CXX \
          --download-openmpi --download-fftw --download-hdf5 --with-hdf5-fortran-bindings=1 --download-zlib \
          --with-mpi-f90module-visibility=1
          make all

      - name: DAMASK - Compile
        run: |
          cmake -B build/grid -DDAMASK_SOLVER=grid -DCMAKE_INSTALL_PREFIX=${PWD}
          cmake --build build/grid --parallel
          cmake --install build/grid
          cmake -B build/mesh -DDAMASK_SOLVER=mesh -DCMAKE_INSTALL_PREFIX=${PWD}
          cmake --build build/mesh --parallel
          cmake --install build/mesh

      - name: DAMASK - Run
        run: |
          ./bin/DAMASK_grid -l tensionX.yaml -g 20grains16x16x16.vti -m material.yaml -w examples/grid
          ./bin/DAMASK_mesh -l tensionZ_3g.yaml -g cube_3grains.msh -m material.yaml -w examples/mesh
